### ISSUE TITLE
create and resume button now working

### ISSUE THREAD

**Issue by 3kulozu** [ctisbtes/btes#9]
**ERROR:**  GET /api/rest/simulationInstanceBroker/create ~> http://localhost:3001
[start:frontend] [HPM] Error occurred while trying to proxy request /simulationInstanceBroker/check?simulationUid=1

**Comment by 3kulozu** [comment]
resolved

**Comment by starikcetin** [comment]
If anyone else comes across the same problem: the new `lodash` dependency introduced in #8 was not installed. A fresh yarn installed solved the problem.
